openapi: 3.0.0
info:
  title: Prime Calculation Task API
  version: '1.0'
  description: API for prime number calculation task

components:
  schemas:
    PrimeCalculationInput:
      type: object
      required: [upper_bound]
      properties:
        upper_bound:
          type: integer
          format: int64
          minimum: 2
          maximum: 1000000000  # 10^9
          description: Calculate all primes up to this number
        batch_size:
          type: integer
          minimum: 1000
          maximum: 1000000
          default: 10000
          description: How many numbers to check in each batch for progress reporting

    PrimeCalculationProgress:
      type: object
      required: [current_number, found_primes]
      properties:
        current_number:
          type: integer
          format: int64
          description: The current number being checked
        found_primes:
          type: integer
          format: int32
          description: Number of primes found so far
        percentage_complete:
          type: number
          format: float
          minimum: 0
          maximum: 100
          description: Percentage of completion
        current_memory_usage:
          type: integer
          format: int64
          description: Current memory usage in bytes
        elapsed_time_ms:
          type: integer
          format: int64
          description: Time elapsed in milliseconds

    PrimeCalculationResult:
      type: object
      required: [primes, execution_stats]
      properties:
        primes:
          type: array
          items:
            type: integer
            format: int64
          description: List of all prime numbers found
        execution_stats:
          type: object
          required: [total_time_ms, max_memory_bytes, numbers_checked]
          properties:
            total_time_ms:
              type: integer
              format: int64
              description: Total execution time in milliseconds
            max_memory_bytes:
              type: integer
              format: int64
              description: Peak memory usage in bytes
            numbers_checked:
              type: integer
              format: int64
              description: Total numbers checked
            average_check_time_ns:
              type: number
              format: float
              description: Average time per number in nanoseconds

paths: {}